name = "Estous"
author = "dots"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cfd9636e3ed4141827793e5feeb22d0ac22b23b7201a04c884c35240df378b2"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
