name = "Estous"
author = "dots"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22e6e7bcb5aa77c0ff38fdef29d9539d12558195e6aadcd237bfd9adfbe2c7de"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
